# Generated by Django 4.1.6 on 2023-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Date', models.CharField(max_length=50)),
                ('Department_name', models.IntegerField()),
                ('Doctor_name', models.CharField(max_length=50)),
            ],
        ),
    ]
