# Generated by Django 4.1.6 on 2023-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
    ]
