# Generated by Django 4.1.6 on 2023-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_medical_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='Date',
            field=models.CharField(max_length=50),
        ),
    ]
