# Generated by Django 4.1.6 on 2023-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_medical_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='medical',
            name='Department_name',
            field=models.IntegerField(choices=[(1, 'Neurology'), (2, 'Cardiology'), (3, 'Eye care'), (4, 'Pediatrics')]),
        ),
    ]
