# Generated by Django 4.1.6 on 2023-03-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_alter_medical_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
