# Generated by Django 4.1.6 on 2023-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
